### ISSUE TITLE
Fable sample

### ISSUE THREAD

**Issue by delneg** [delneg/fable-sqljs-absurdsql#1]
@alfonsogarciacaro Please see if this app can be useful as a fable sample (in fable3-samples repo) or smth like that

**Comment by alfonsogarciacaro** [comment]
Didn't know about the sql.js project. Indeed it can be really interesting for Fable devs (although the name picked by the author of absurd-sql can be quite misleading), either in fable3-samples repo or on its own repo and adding it to [Resources in fable.io](https://fable.io/resources.html#Examples), or even writing [a post](https://fable.io/blog/) about Fable and sql.js.

**Comment by delneg** [comment]
> Didn't know about the sql.js project. Indeed it can be really interesting for Fable devs (although the name picked by the author of absurd-sql can be quite misleading), either in fable3-samples repo or on its own repo and adding it to [Resources in fable.io](https://fable.io/resources.html#Examples), or even writing [a post](https://fable.io/blog/) about Fable and sql.js.

Thanks!
Indeed, the opportunities presented by the possibility to use SQL on the web are great.
However, the library seems incomplete without some sort of example usage of the DSL for F# - i.e. Donald or SqlHydra. I've asked a question about that on [Twitter](https://twitter.com/DelnegOfficial/status/1454761815343259649), but haven't received any replies yet.
I'll be submitting a PR to fable samples soon anyway.
This repo itself can be renamed to Fable-SQLjs for simplicity, with the links to original author & other libs in README.

**Comment by delneg** [comment]
@alfonsogarciacaro 
Done in https://github.com/fable-compiler/fable3-samples/pull/12
